package com.easy.exception;

public class ErrorCode {
	public final static String ErrorCode00 = "代码:00;数据已接收！";
	public final static String ErrorCode01 = "代码:01;没有符合条件的数据！";
	public final static String ErrorCode02 = "代码:02;没有符合删除的数据！";
	public final static String ErrorCode03 = "";
	public final static String ErrorCode04 = "";
	public final static String ErrorCode05 = "";
	public final static String ErrorCode06 = "";
	public final static String ErrorCode07 = "";
	public final static String ErrorCode08 = "";
	public final static String ErrorCode09 = "";
	public final static String ErrorCode10 = "";
	public final static String ErrorCode29 = "";
	public final static String ErrorCode30 = "";
	public final static String ErrorCode31 = "代码:31;通道调用失败！";
	public final static String ErrorCode32 = "代码:32;报文格式不正确！";
	public final static String ErrorCode33 = "";
	public final static String ErrorCode34 = "";
	public final static String ErrorCode35 = "代码:35;请求验证不通过！";
	public final static String ErrorCode36 = "代码:36;权限不足，请联系平台解决！";
	public final static String ErrorCode37 = "代码:37;请求参数不能为空！";
	public final static String ErrorCode38 = "代码:38;MQ配置无效！";
	public final static String ErrorCode39 = "代码:39;通信帐号密码验证失败！";
	public final static String ErrorCode40 = "代码:40;数据累加超过上限!";
	public final static String ErrorCode41 = "";
	public final static String ErrorCode42 = "";
	public final static String ErrorCode43 = "";
	public final static String ErrorCode44 = "";
	public final static String ErrorCode45 = "";
	public final static String ErrorCode46 = "";
	public final static String ErrorCode47 = "";
	public final static String ErrorCode48 = "";
	public final static String ErrorCode49 = "";
	public final static String ErrorCode50 = "";
	public final static String ErrorCode51 = "";
	public final static String ErrorCode52 = "";
	public final static String ErrorCode53 = "";
	public final static String ErrorCode54 = "";
	public final static String ErrorCode55 = "";
	public final static String ErrorCode56 = "";
	public final static String ErrorCode57 = "";
	public final static String ErrorCode58 = "";
	public final static String ErrorCode59 = "代码:59;通信帐号密码验证失败！";
	public final static String ErrorCode60 = "代码:60;数据接入错误！";
	public final static String ErrorCode61 = "代码:61;通道调用失败！";
	public final static String ErrorCode62 = "代码:62;报文格式不正确！";
	public final static String ErrorCode63 = "代码:63;业务验证不通过！";
	public final static String ErrorCode64 = "代码:64;字段验证不通过！";
	public final static String ErrorCode65 = "代码:65;请求验证不通过！";
	public final static String ErrorCode66 = "代码:66;报文加签失败！";
	public final static String ErrorCode67 = "";
	public final static String ErrorCode68 = "";
	public final static String ErrorCode69 = "";
	public final static String ErrorCode90 = "";
	public final static String ErrorCode91 = "";
	public final static String ErrorCode92 = "";
	public final static String ErrorCode93 = "";
	public final static String ErrorCode94 = "";
	public final static String ErrorCode95 = "代码:95;平台参数设置出错！";
	public final static String ErrorCode96 = "代码:96;权限不足，请联系平台解决！";
	public final static String ErrorCode97 = "代码:97;请求参数不能为空！";
	public final static String ErrorCode98 = "代码:98,数据删除成功！";
	public final static String ErrorCode99 = "代码:99;消息遇到未知错误！";
	
	
}
